[package]
name = "ic_siwb_provider"
version = "0.0.1"
edition = "2021"
authors = ["ghostcorn <ghostcorn@astrox.network>"]
description = "Using the pre built ic_siwb_provider canister is the easiest way to integrate Bitcoin wallet authentication into an Internet Computer (ICP) application."
license = "MIT"
homepage = "https://github.com/AstroxNetwork/ic-siwb"
repository = "https://github.com/AstroxNetwork/ic-siwb"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.20"
ic-cdk = "0.18.7"
ic_siwb = { path = "../ic_siwb" }
ic-stable-structures = "0.7.2"
ic-certified-map = "0.4.1"
serde = "1.0.228"
serde_json = "1.0"
serde_bytes = "0.11"


# [dev-dependencies]
# Commented out to avoid ic-cdk version conflicts in workspace
# ethers = "2.0.10"
# hex = "0.4.3"
# ic-agent = "0.37.1"
# pocket-ic = "5.0.0"
# siwe = "0.6"
# rand = "0.9.2"
# ring = "0.17.12"
